### ISSUE TITLE
Missing python module "overtherepy"

### ISSUE THREAD

**Issue by bjartenilsen** [xebialabs-community/xld-ansible-step-plugin#2]
Hi, I just installed xld-ansible-step-plugin-1.1.0-rc.7.xldp - Using XLD Server version: 9.5.1 (docker edition)  and got an error when connecting to controller. Missing a module. 

Is this something I need to add to the default XLD docker container? Or a bug in this code? 

Error while executing script [upload_ssk_key.py]: ImportError: No module named overtherepy in <script> at line number 11
com.xebialabs.platform.script.jython.JythonException: Error while executing script [upload_ssk_key.py]: ImportError: No module named overtherepy in <script> at line number 11
	at com.xebialabs.platform.script.jython.JythonException$.apply(JythonException.scala:17)
	at com.xebialabs.platform.script.jython.JythonSupport.$anonfun$executeScript$3(JythonSupport.scala:60)
	at com.xebialabs.platform.script.jython.JythonSupport.withThreadLocalWriter(JythonSupport.scala:67)
	at com.xebialabs.platform.script.jython.JythonSupport.executeScript(JythonSupport.scala:56)
	at com.xebialabs.platform.script.jython.JythonSupport.executeScript$(JythonSupport.scala:53)
	at com.xebialabs.deployit.plugin.steps.JythonStep$$anon$1.executeScript(JythonStep.scala:29)
	at com.xebialabs.platform.script.jython.JythonSupport.executeScript(JythonSupport.scala:50)
	at com.xebialabs.platform.script.jython.JythonSupport.executeScript$(JythonSupport.scala:44)
	at com.xebialabs.deployit.plugin.steps.JythonStep$$anon$1.executeScript(JythonStep.scala:29)
	at com.xebialabs.deployit.plugin.steps.JythonStep.executeScript(JythonStep.scala:67)
	at com.xebialabs.deployit.plugin.steps.JythonStep.execute(JythonStep.scala:58)
	at com.xebialabs.deployit.engine.tasker.StepExecutingActor.$anonfun$executeStep$3(StepExecutingActor.scala:144)
	at com.xebialabs.deployit.engine.tasker.MdcUtils$.withMdc(MdcUtils.scala:16)
	at com.xebialabs.deployit.engine.tasker.StepExecutingActor.$anonfun$executeStep$2(StepExecutingActor.scala:134)
	at scala.concurrent.Future$.$anonfun$apply$1(Future.scala:658)
	at scala.util.Success.$anonfun$map$1(Try.scala:255)
	at scala.util.Success.map(Try.scala:213)
	at scala.concurrent.Future.$anonfun$map$1(Future.scala:292)
	at scala.concurrent.impl.Promise.liftedTree1$1(Promise.scala:33)
	at scala.concurrent.impl.Promise.$anonfun$transform$1(Promise.scala:33)
	at scala.concurrent.impl.CallbackRunnable.run(Promise.scala:64)
	at akka.dispatch.BatchingExecutor$AbstractBatch.processBatch(BatchingExecutor.scala:55)
	at akka.dispatch.BatchingExecutor$BlockableBatch.$anonfun$run$1(BatchingExecutor.scala:92)
	at scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.java:23)
	at scala.concurrent.BlockContext$.withBlockContext(BlockContext.scala:85)
	at akka.dispatch.BatchingExecutor$BlockableBatch.run(BatchingExecutor.scala:92)
	at akka.dispatch.TaskInvocation.run(AbstractDispatcher.scala:41)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
Caused by: javax.script.ScriptException: ImportError: No module named overtherepy in <script> at line number 11
	at org.python.jsr223.PyScriptEngine.scriptException(PyScriptEngine.java:222)
	at org.python.jsr223.PyScriptEngine.eval(PyScriptEngine.java:59)
	at org.python.jsr223.PyScriptEngine.eval(PyScriptEngine.java:31)
	at com.xebialabs.platform.script.jython.JythonSupport.$anonfun$executeScript$3(JythonSupport.scala:57)
	... 28 more
Caused by: Traceback (most recent call last):
  File "<script>", line 11, in <module>
ImportError: No module named overtherepy
	at org.python.core.Py.ImportError(Py.java:334)
	at org.python.core.imp.import_first(imp.java:879)
	at org.python.core.imp.import_module_level(imp.java:964)
	at org.python.core.imp.importName(imp.java:1057)
	at org.python.core.ImportFunction.__call__(__builtin__.java:1280)
	at org.python.core.PyObject.__call__(PyObject.java:450)
	at org.python.core.__builtin__.__import__(__builtin__.java:1232)
	at org.python.core.imp.importFromAs(imp.java:1149)
	at org.python.core.imp.importFrom(imp.java:1124)
	at org.python.pycode._pyx1634.f$0(<script>:29)
	at org.python.pycode._pyx1634.call_function(<script>)
	at org.python.core.PyTableCode.call(PyTableCode.java:171)
	at org.python.core.PyCode.call(PyCode.java:18)
	at org.python.core.Py.runCode(Py.java:1614)
	at org.python.core.__builtin__.eval(__builtin__.java:497)
	at org.python.core.__builtin__.eval(__builtin__.java:501)
	at org.python.util.PythonInterpreter.eval(PythonInterpreter.java:259)
	at org.python.jsr223.PyScriptEngine.eval(PyScriptEngine.java:57)
	... 30 more

**Comment by bjartenilsen** [comment]
I found the missing jar file here https://github.com/xebialabs-community/overthere-pylib and added the latest release to my xld instance. That made it work. I was not aware of this library and the dependency to it.
